[profile.release]
lto = true
opt-level = "s"
panic = "abort"

[workspace]
members = [
    "skeleton-app",
    "target/hyperapp-skeleton-caller-utils",
    "target/hyperapp-skeleton-caller-util?",
]
resolver = "2"
